apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: k-s-pod-identity-controller
build:
  artifacts:
    - image: cloud-role-identity-controller
deploy:
  helm:
    releases:
      - name: cloud-role-identity-controller
        chartPath: chart
        setValueTemplates:
          image.repository: "cloud-role-identity-controller"
          image.tag: "latest"
        valuesFiles:
          - chart/values.yaml
        version: 0.1.0
